### ISSUE TITLE
GUI integration on the deal

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#5]
- [ ] when started, gui renders the board with empty cells and dealt cards in place (or an animation if you're feelin snappy).

- [x] attach buttons to the action handlers in engine.Engine.  they can remain empty for now.

- [ ] start thinking about how you're going to integrate the mouse events with engine.Turn.guiTurn and makeMove.  the turn constructor separates cli from gui for input (.cliTurn and .guiTurn), and they converge again in makeMove.  makeMove only requires a mapping to proceed (ref: cliTurn).

**Comment by st01k** [comment]
getting this, are you?

`<<<< Freecell CLI v0.1 >>>>
Type 'help' for commands.
Type 'exit' any time.

freecell> gui
Exception in thread "main" java.lang.NullPointerException
	at client.gui.FreeGUI.Paint(FreeGUI.java:49)
	at engine.Engine.gameLoop(Engine.java:58)
	at engine.Engine.start(Engine.java:42)
	at client.cli.CLI.prompt(CLI.java:60)
	at client.Driver.main(Driver.java:27)`
